version: '3'

services:
  aesm:
    image: cashmaney/aesm
    devices:
      - /dev/sgx
    volumes:
      - /tmp/aesmd:/var/run/aesmd
    stdin_open: true
    tty: true

  app:
    image: cashmaney/sgx_signer
    depends_on:
      - aesm
    devices:
      - /dev/sgx
    volumes:
      - /tmp/aesmd:/var/run/aesmd
    stdin_open: true
    tty: true
    environment:
      NODE_ADDRESS