#!/bin/bash
# This `DEBIAN/postinst` script is run post-installation

set -e

USER=$(whoami)

mkdir -p /opt/.signer/config
mkdir -p ~/.signer/watermark/
mkdir -p ~/.signer/config/

mv /opt/tendermint-validator/config.toml ~/.signer/config/config.toml
mv /opt/tendermint-validator/priv_validator_state.json ~/.signer/watermark/priv_validator_state.json

if id -u $USER > /dev/null 2>&1; then
    chown ${USER}:${USER} -R ~/.signer
fi

perl -i -pe "s/replace_username/$USER/" ~/.signer/config/config.toml

cat <<EOF > /etc/systemd/system/validator-node.service
[Unit]
Description=Tendermint Validator Node Service
After=network.target

[Service]
Type=simple
ExecStart=$(which signer) --config /home/$(whoami)/.signer/config/config.toml
User=$(whoami)
Restart=always
StartLimitInterval=0
RestartSec=3
LimitNOFILE=500000

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload

sudo perl -i -pe 's/#SystemMaxUse=.*/SystemMaxUse=50M/' /etc/systemd/journald.conf
sudo systemctl restart systemd-journald