[dependencies]
alloc = {}
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 1 }
sgx_alloc = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 1 }
sgx_unwind = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 1 }
sgx_demangle = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 1 }
panic_abort = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 1 }
sgx_libc = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 2 }
sgx_tkey_exchange = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 2 }
sgx_tse = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 2 }
sgx_tcrypto = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 2 }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 3 }
sgx_backtrace_sys = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 3 }
panic_unwind = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 3 }
sgx_tdh = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 4 }
sgx_tseal = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 4 }
sgx_tprotected_fs = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 4 }
std = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 5, features = ["net", "backtrace", "untrusted_fs"] }
sgx_no_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 5 }
sgx_rand = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 6 }
sgx_serialize = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 6 }
sgx_tunittest = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 6 }
sgx_backtrace = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 7 }
sgx_cov = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 7 }
sgx_signal = { git = "https://github.com/apache/teaclave-sgx-sdk.git", rev = "v1.1.2", stage = 7 }
